coverage:
  status:
    # main branch
    project:
      default:
        target: auto
        informational: true
        threshold: 100%

    # PRs
    patch:
      default:
        target: auto
        informational: true
        threshold: 100%

comment: false

github_checks:
  annotations: false

ignore:
  - "docs"
  - "examples"
  - ".github"
