name: Lint and test

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools
          pip install .[dev]

      - name: Lint 🔍
        run: ./tests/lint.sh

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools
          pip install -U twine build

      - name: Check bundling 📦
        run: python -m build

      - name: Check setup 🚦
        run: twine check "dist/order-*.tar.gz"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    name: test (python ${{ matrix.python-version }})
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools
          pip install .[dev]

      - name: Test 🎢
        run: ./tests/test.sh

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install dependencies ☕️
        run: |
          pip install -U pip setuptools
          pip install .[dev]

      - name: Run coverage test 🎢
        run: |
          pytest --cov=order --cov-report xml:coverage.xml tests

      - name: Upload report 🔝
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
